spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  kafka:
    # Kafka 서버 접속 주소 (Docker compose의 PLAINTEXT_HOST 포트)
    bootstrap-servers: localhost:9092
    producer:
      #	프로듀서 키 직렬화 방식
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 프로듀서 값 직렬화 방식
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: my-group
      # 초기 오프셋 설정 (가장 처음부터 메시지 소비)
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



# swagger-ui 설정
#swagger-ui 접속 경로(http://localhost/swagger-ui/index.html)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true

  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application